### ISSUE TITLE
onChange/onComplete not firing when width or height of crop are change programmatically

### ISSUE THREAD

**Issue by billneff79** [DominicTobias/react-image-crop#102]
onChange and onComplete are not being fired if new crops.width or crops.height props are passed to the component.  They only appear to be fired on user interaction.  I need to be able to get the pixelCrop after the crop occurs if I update those values programatically.

**Comment by DominicTobias** [comment]
The problem with implementing this is that it goes against some common React principles that I didn't properly adopt when first building this library, but may want to change in the future.

At the moment state is held internally in ReactCrop - this means that you don't have to implement the onChange handler.

Think about when you use an `<input>` in react - if you don't implement the `onChange` callback then you get a warning about the component being "uncontrolled". https://facebook.github.io/react/docs/uncontrolled-components.html

> In most cases, we recommend using controlled components to implement forms.

This is because React component design prefers to shift state upwards - so really you should not be able to move the ReactCrop's crop area without implementing `onChange`, since ReactCrop shouldn't hold any state, it should just be told what to do by the parent:

_ReactCrop onChange -> set new crop in your component state -> causes a re-render of ReactCrop with new crop_

So at some point I am planning to move to this architecture, and if I also called `onChange`/`onChangeComplete` when new props are passed in, then it would cause an infinite loop!

I won't change this until a major version but I don't want people to get used to something and then change it later down the line.

So for now since you are changing the crop programatically you know a change happened, so you can still do logic at that point. Sorry!

**Comment by billneff79** [comment]
That's OK.  We ended up calculating the change programmatically instead of
reacting to an onChange handler.

**Comment by DominicTobias** [comment]
Great 👍
