### ISSUE TITLE
Cannot resize it

### ISSUE THREAD

**Issue by barbu110** [DominicTobias/react-image-crop#108]
It would be very useful to be able to size the component the way you need it, like if you load a 16:9 image, specify a width of `800px` and that's it. Currently, the interface will expand the whatever the image size is which is not quite ok. 

**note** There is an expensive workaround to this that I can think of, resize the image in-browser and create the blob URL for it afterwards. 

Any other suggestions?

**Comment by DominicTobias** [comment]
Hi thanks for this. But I don't this will work for the largest use case which is delivering an image from a server and then cropping it on the server. The backend does not know how the image was distorted in the browser.

The idea if that you send the crop x & y as a percentage to the server and it can crop the image, regardless of the size of the image on the client (whether it was made bigger or smaller). All this is dependent on is that you do not distort the image (maintain the origin aspect), which I do not see why you would?? The usual thing would be to put the image in a container, and allow it to go only as large as the container - though you could size up if you wanted to I suppose.

What is your use case for specifying both the width and height of the image?

You might be right though that it's better to use `width` and `height` rather than `naturalWidth` and `naturalHeight`, as the `pixelCrop` would be incorrect if the image is resized!

**Comment by DominicTobias** [comment]
Hi the intention is that you limit the crop from the container, and allow the crop to expand up to that:

```react
<div style="width: 500px"><ReactCrop .../></div>
```

This container could be limited by other things e.g. a percentage or flexbox etc.
