### ISSUE TITLE
Read base64 of Cropped image

### ISSUE THREAD

**Issue by Sirbuland** [DominicTobias/react-image-crop#209]
I can read the base64 of full image but when cropping is complete how I can get the base64 of cropped image?

**Comment by DominicTobias** [comment]
Hi take a look at the readme it shows you how to do it - https://github.com/DominicTobias/react-image-crop#what-about-showing-the-crop-on-the-client

**Comment by ShanonJackson** [comment]
@DominicTobias, really appreciate all the work you've done on this to keep the file size small etc but that example you have doesn't even work to get base64 back. Here is a sandbox implementing your example.
https://codesandbox.io/s/04w6mvpwm0

It doesn't work because crop passes back percentage based X/Y but drawImage expects PX based X/Y on top of that even using a px based X/Y i still can't get it working.


Please provide a working sandbox to get a Base64 image back for images of all dimensions.

**Comment by DominicTobias** [comment]
Hi @ShanonJackson the second argument to onChange is the pixel crop values, https://github.com/DominicTobias/react-image-crop#onchangecrop-pixelcrop-required try with that

**Comment by DominicTobias** [comment]
I've edited your example and will link to that on the readme instead - https://codesandbox.io/s/72py4jlll6

**Comment by tragicmj** [comment]
@DominicTobias getting this error ×
Unhandled Rejection (SecurityError): Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.

 And on adding crossorigin anonymous the image is not showing coming as broken

**Comment by DominicTobias** [comment]
> @DominicTobias getting this error × Unhandled Rejection (SecurityError): Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.
> 
> And on adding crossorigin anonymous the image is not showing coming as broken

I can’t remember how to fix this or if it’s fixable for remote images but it’s a general issue with the browser security - nothing I can do from this component - if you tried to do this outside the component on a img you’d get the same error

**Comment by Gorett** [comment]
Hi from 2023. Your library is light but difficult to use. I've spend 2 hours trying to use it. Unfortunately it's useless without existed ability of getting a cropped image. Eventually, I found this `react-cropper` package. It took me 10 mins to complete everything. Barely somebody needs cropping package without easy ability to get the final result.
