### ISSUE TITLE
Is there a way to defaultly select the whole image when image load?

### ISSUE THREAD

**Issue by kidmysoul** [DominicTobias/react-image-crop#230]
Thanks for the awsome library.

 I want to defaultly select the whole image(which means defaultly  crop none) when image load, How can i achieve this ?

**Comment by DominicTobias** [comment]
Hi, do you mean you don't want a crop when the image loads? Simply don't pass in a `crop` prop, or have the values inside it set to 0.

**Comment by kidmysoul** [comment]
@DominicTobias 
Thank you for reply. I mean I need a crop which defaultly select the whole image . I want to show the moving dot line around the whole image ....

Do I have to pass the exact width and height to crop image ?

**Comment by kidmysoul** [comment]
@DominicTobias 
Thankyou, I will give it a try.

**Comment by DominicTobias** [comment]
Great!

**Comment by HelgaSokolova** [comment]
I have same problem here. Seems like crop is not percentage but pixel at the moment, is this wrong?

**Comment by DominicTobias** [comment]
@HelgaSokolova you are correct, however v8 which has a beta release will have the best of both worlds and be able to specify either. For v7 for now you can wait to set the crop until `onImageLoaded` and set it in there, since you have access to `image.width` and `image.height` in there.

**Comment by HelgaSokolova** [comment]
Thank you @DominicTobias. For now, ```{width: 5000, height: 5000}``` solved my problem on V7. :D
For your suggestion of V7, which method should I call to update `crop`? I've tried with `setState({crop: { width: image.width })` but this didn't help me.

**Comment by DominicTobias** [comment]
Hah yeah that would work too. I meant something like this:

```js
onImageLoaded = image => {
  this.setState({ crop: { width: image.width, height: image.height } });
}
```

```js
<ReactCrop
  onImageLoaded={this.onImageLoaded}
```

**Comment by HelgaSokolova** [comment]
Yes, your code didn't help me. I guess I should call that after some delay. In any case, thank you for your support! Look forward to v8!

**Comment by bogdansoare** [comment]
@DominicTobias the problem with the `onImageLoaded` callback is fired before `onChange` making it useless for setting the crop based on the image dimensions

**Comment by DominicTobias** [comment]
@bogdansoare there are a couple of ways to achieve this:

Option 1)

Calling onChange/onComplete before onImageLoaded event doesn't work because setting state is asynchornous, imagine:

- the image loaded
- fire onChange/onComplete, you call setState here
- onImageLoaded called straight after = your state is still on the previous values

Instead you should return false in onImageLoaded:

```js
onImageLoaded = image => {
  this.setState({ crop: { width: image.width, height: image.height } });
  return false;
}
```

This will stop onChange/onComplete being fired, but since you setState it will get fired when the state has actually updated. I forgot to mention that in the above comment ^^

Option 2)

Using v8 you don't need to wait for image load and can pass a percentage to begin with:

```js
crop: {
  unit: '%',
  width: 100,
  height: 100,
}
```

**Comment by bogdansoare** [comment]
@DominicTobias thank you very much for the suggestions, I think I'm going with option 1, because I want to force the aspect to be 1 and from what I can see doing
```js
crop: {
  unit: '%',
  aspect: 1
  width: 100,
}
```
doesn't keep the aspect ratio 1 if the width is bigger than the height

**Comment by DominicTobias** [comment]
You should actually be able to do that by doing: `crop: { unit: '%', aspect: 1, width: 100 }` (or height) and that would be full height or width, and then make up the other side so that it was still a square. But I noticed that auto-completing the aspect crop if one side isn't specified is not working maybe I broke it in v8. Will take a look soon - so yes for now best to do the calc yourself.

**Comment by bogdansoare** [comment]
understood, thanks 👍
