### ISSUE TITLE
[Question] How to make it work with react-dropzone?

### ISSUE THREAD

**Issue by fzs1994** [DominicTobias/react-image-crop#286]
How to make it work with [React Dropzone](https://github.com/react-dropzone/react-dropzone) ?

**Comment by DominicTobias** [comment]
You didn't specify what you meant by "making it work" and since I haven't used DropZone I can't say - out of scope of issues for this lib and best to ask on Stackoverflow.

However since this library can take any image, including one made from base64 data or a blob URL I would imagine you can get that out of DropZone quite easily.
