### ISSUE TITLE
Width and height are not equal on ratio 1/1 and scaled to natural img size

### ISSUE THREAD

**Issue by dominikkurbiel** [DominicTobias/react-image-crop#315]
Hey ;)

I have an image with original size 1200x628. But I display it in a cropper with size of 906x474. I need to crop this image with ratio 1/1 ( square) and save the cropped square as base64 but with right width/height based on natural image size.

So when I'm selecting a square with size of 474x474. The natural cropped size should be 628x628 but actually it is (627.8145695364238 x 628).

You can see it here: https://codesandbox.io/s/react-image-crop-demo-ee68j

Try to upload any image, crop the image and see the values of naturalCrop and currentCrop above the file upload button.

How to crop the image by natural size but with right width and height?

**Comment by DominicTobias** [comment]
Hi, in the code you are scaling up the crop preview to the original image size:

```
const cropWidth = crop.width * scaleX;
const cropHeight = crop.height * scaleY;
```

This is causing a small amount of imprecision by the browser - why I can't say I'm not a browser or floating point in javascript expert ;) If you remove the scale up the imprecision is gone:

```
const cropWidth = crop.width;
const cropHeight = crop.height;
```

Since you know the image should be a square you could maybe floor these numbers down to the closest pixel, but again not sure the best way to solve that it's beyond this library.
