### ISSUE TITLE
Make it clearer to the developer when they are passing in an invalid `crop` object

### ISSUE THREAD

**Issue by ericbiewener** [DominicTobias/react-image-crop#327]
The DefinitelyTyped typings indicate that all `Crop` properties are optional even though this is only the case the first time you pass in the `crop` prop to the component. Passing in an invalid `crop` object after initialization produces a variety of weird things, such as no crop marquee appearing, `NaN` values for `x` or `y` when dragging, inability to resize from certain corners. Although the documentation does explain that all properties are required after initialization, the lack of console error messages or sufficiently strict typings makes it a bit difficult to figure out what's going wrong.

The most straightforward solution would be to make all the properties required upon initialization. If that's not desirable, providing some dev warnings when an invalid object is provided would be helpful, as would fixing the typings.

**Comment by DominicTobias** [comment]
Hi, the reason crop properties are optional is because initially there can be no crop. However I wonder if it's possible to make these properties required, but the overall object optional. I don't know much about TS and don't maintain the typings it's a third party contribution so feel free to improve it.

As per crop values there are the typings plus prop-types (https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.js#L875). After the initial load it should be pretty difficult to pass in invalid values since you are passing in the values from the `onChange` function. I'm not sure what other validation it needs - what were passing in for the initial crop object to produce such NaN values?

**Comment by ericbiewener** [comment]
> After the initial load it should be pretty difficult to pass in invalid values
I'm doing it in `onImageLoaded`, which I imagine is a fairly common use case. I could also imagine buttons that allow users to set certain aspect ratios.

Unfortunately I have had to shift off the feature using this library so I'm not able to keep digging into this. My code is no longer in a state that is producing the `NaN` values, and I'm actually finding that I don't need to provide all crop values after all. So perhaps I was providing some set of invalid or conflicting values when I was getting the `NaN` results.

Sorry, I wouldn't have opened the issue if I knew that I wouldn't have the chance to fully engage with it! I'll go ahead and close this and will chime back in once I'm able to continue working on this feature.
