### ISSUE TITLE
How to have cropping from all 4 sides in mobile screens ?

### ISSUE THREAD

**Issue by mashish584** [DominicTobias/react-image-crop#342]

**Comment by DominicTobias** [comment]
Hi you can pin the version to 8.3.1 or possibly take the CSS from there and use the new version (haven't tested that). The library no longer supports 4 sides on mobile due to the difficulty of fingers grabbing the smaller boxes, you can see the release notes for 8.4.0 here - https://github.com/DominicTobias/react-image-crop/releases

**Comment by DominicTobias** [comment]
Might reconsider this actually, will re-open and update

**Comment by DominicTobias-b1** [comment]
Added back in 8.6.0 (published in 5mins)

**Comment by mtjn** [comment]
Hey, is this configurable - is there a prop to choose between the four-point style or the right-corner style? Or is 4-corner style the only option.

Thanks!

**Comment by DominicTobias-b1** [comment]
Hi @mtjn it isn't at the moment but could make it in a future release. You can do it with pure CSS though - hide all the other handles in CSS and make the bottom right one larger
