### ISSUE TITLE
The return of "Error: Maximum update depth exceeded."

### ISSUE THREAD

**Issue by jamsinclair** [DominicTobias/react-image-crop#347]
Perhaps related to #218 

When using `percentageCrop` and adjusting the crop selection in certain circumstances this error is thrown:
> Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

I have created a variant of your hooks demo in which you can usually replicate this bug. 

### Reproduction Steps (Updated. 
1. Go to https://codesandbox.io/s/strange-lalande-91wgp
1. Click "Set bad crop data" in rendered view
1. Error: Maximum update depth exceeded should be thrown

**Example of reproduction:**
![maximum-update-bug](https://user-images.githubusercontent.com/5964236/78741992-bf03b280-7995-11ea-99f4-a4ecaec973bf.gif)

If I get a spare moment, I'll see if I can help debug further for you!

**Edit:** I've updated the example with buggy crop data that should trigger an infinite loop on update.

**Comment by DominicTobias-b1** [comment]
Hey thanks I was worried about this since I added "completing aspect crops" on componentDidUpdate. The idea was the make it easier to make a percentage aspect crop without having to do some maths yourself.

// isAspectCropInvalid 
https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.js#L126

// componentDidUpdate
https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.js#L285

The problem is probably that the library thinks that the aspect crop is invalid over and over again and keeps trying to correct it due to imprecision when converting percentage to pixels. What browser and version is that by the way?

**Comment by jamsinclair** [comment]
Thanks @DominicTobias @DominicTobias-b1! That makes sense. 

Currently experiencing this on:
MacOS Catalina 10.15.4
Chrome Version 81.0.4044.92 (Official Build) (64-bit)

**Comment by 209** [comment]
Hi! This issue is very often reproduced with browser zoom.

**Comment by jamsinclair** [comment]
I've updated the example so the bug is 100% reproducible with a button click. 

I captured the bad crop data just before the error is thrown. Replaying this crop data with the image at the same size causes the infinite update loop.

See https://codesandbox.io/s/strange-lalande-91wgp again, hopefully makes debugging easier!

**Comment by DominicTobias** [comment]
Thanks @jamsinclair please try 8.6.2

**Comment by DominicTobias** [comment]
It will take a little while for codesandbox to pick up the new version

**Comment by pdandradeb** [comment]
I've updated to 8.6.2 and couldn't reproduce the error anymore. Thanks for the work, @DominicTobias!

**Comment by jamsinclair** [comment]
Likewise, cannot reproduce 👌 . However I do suspect there may be some weird edgecases where the infinite update will still happen. As a future improvement might be good to guard against that in `componentDidUpdate`... however perhaps not needed. 

 @DominicTobias Regardless many many thanks! You're an amazing maintainer, hope things are ok in these uncertain times! ❤️
