### ISSUE TITLE
[Suggestion] Add Optional Rulers/Axis

### ISSUE THREAD

**Issue by Benny121221** [DominicTobias/react-image-crop#361]
In the below MS Paint screenshot, you can see on the left and top edges of the frame "rulers" or axes which correspond to pixel coordinates.

In an unrelated, but perhaps similarly useful feature, it also gives the coordinates of the mouse cursor in the bottom left.

![image](https://user-images.githubusercontent.com/8635304/83831367-7ec66500-a6a4-11ea-9ba3-9bf684e14ce5.png)

Apologies for my poor handwriting, I hope it doesn't cause you any trouble.

MS Paint also has the option to give these in both inches and centimetres, but I don't know how friendly canvas is towards differing DPIs (or even absolute measurement).

![image](https://user-images.githubusercontent.com/8635304/83831676-280d5b00-a6a5-11ea-9674-ff9020101564.png)
![image](https://user-images.githubusercontent.com/8635304/83831732-3fe4df00-a6a5-11ea-9c91-e4d4e49e47b2.png)

**Comment by Benny121221** [comment]
I added a basic thing on my fork: https://github.com/Benny121221/react-image-crop/tree/ruler

I had assumed you were using canvas, but since you weren't I decided to stick with just plain CSS. It might be a good idea to use canvas or svg if you want to add any more to it

**Comment by DominicTobias-b1** [comment]
Hi while this is a nice idea I don't plan on working on it sorry. If I was doing it I would probably make it a separate component that can wrap around anything e.g.

```js
<Rulers><ReactCrop /><Rulers />
```

Since it's not hard to observe the height of the rule div and let it adjust to the size of the content it's wrapping, as well as listen for mouse movement.

Going to close as I won't work on it but feel free to post any updates/questions.
