### ISSUE TITLE
CORS issue while adding src of a public GCP bucket

### ISSUE THREAD

**Issue by wasifali** [DominicTobias/react-image-crop#390]
While using the `ReactCrop` I'm giving a public image url to `src`
Image Url: https://storage.googleapis.com/milkyway-cpgapp/98889-9dPf8sFFuNdEL4Oz0B6F.jpg

what the issue I'm facing is 
![cors-error](https://user-images.githubusercontent.com/15184858/95709279-c1fa9b00-0c77-11eb-8e8d-d3853a411514.png)

Unable to find any solution for this, any help will  be highly appreciated.
Thanks

**Comment by juanitoddd** [comment]
Hello, I am having the same issue, any ideas why this is happening ?
Regards

**Comment by AndiswamyDev** [comment]
@DominicTobias , Do you have any suggestions to get rid of this issue, Coz I tried to fetch s3 image url and getting cors and  stuck up with it.

**Comment by GustavoGottardi** [comment]
@DominicTobias I have the same error when tried to fetch S3 image url, could you help us? :/

**Comment by DominicTobias** [comment]
All the library does is insert the image url in a normal image element so if it's not working in that then it's not working in a normal image either I would assume, so in other words it's not related to the library but how S3 buckets work - you need to return an Access-Control-Allow-Origin header which permits the image being loaded from other domains.

Or otherwise only thing I can think of is using the `crossOrigin` attribute of the image, try setting:

```jsx
<ReactCrop crossOrigin="anonymous" ... />
```

Otherwise you need to return the correct access control header from your S3 bucket - https://www.google.com/search?q=s3+image+bucket+Access-Control-Allow-Origin&oq=s3+image+bucket+Access-Control-Allow-Origin&aqs=chrome..69i57.1778j0j7&sourceid=chrome&ie=UTF-8

Closing as a general issue with S3 images not related to this lib and I don't have exp fixing that
