### ISSUE TITLE
Inline Styles

### ISSUE THREAD

**Issue by DanlanNZ** [DominicTobias/react-image-crop#4]
what are your thoughts on using inline styles for this component? any objections if I implement it?

**Comment by DominicTobias** [comment]
Hi @DanlanNZ, thanks I really appreciate the offer but not sure about inline styles as at the moment people can override the look of the crop, but this would make it more difficult.

Admittedly it's not something that most projects want to change however there are some alternative looks for crops like http://dev.vizuina.com/cropper/ and https://fengyuanchen.github.io/cropper/ out there.

I do get though that having the styles inline means that people can just import the library and not worry about importing the css, but it's a question of convenience vs customisability, and I'm leaning towards customisability!

**Comment by DanlanNZ** [comment]
thanks for getting back to me so quickly @DominicTobias, I believe inline styles can provide a similar level of customisability by providing multiple style tags (e.g. style, selectionStyle) then assigning these to the component (using Object.assign or similar) overriding the defaults were necessary.

Material-UI does this well https://github.com/callemall/material-ui/blob/master/src/icon-button.jsx

There is also a great library for helping to manage inline styles http://projects.formidablelabs.com/radium/ it could work well

**Comment by DominicTobias** [comment]
Yeah Radium looks good as it handles cases inline styles can't handle like pseudo classes. However it's almost 40kb minified so it's just too large of a dependency to demand of somebody using this tool.

The material UI looks like for each style it merges with a prop, so the styles are overridable and so that seems like a reasonable idea. My concern is how much additional code what be needed, but possible not much for the Material UI way. But also again flexibility - if a user wanted to do something on hover for instance it wouldn't be possible without the Radium heavy-weight solution of wrapping the render method and iterating over elements and adding onMouseOver events etc.

**Comment by DominicTobias** [comment]
Feel free to create a fork with your ideas if you want, I just can't say whether I would merge it or not as I'm not sure if it's a good idea yet :)

**Comment by DanlanNZ** [comment]
point taken re. Radium's size, bit of an overkill for a small component. I took a stab at implementing the Material-UI style solution over the weekend and opened a pull request #5 for you to review.

Functionality is at a similar level to SASS styling but without responsive styles. I could implement this on componentWillMount() using window.innerWidth but it's a bit of an overkill IMHO. Hover events could be implemented with an onMouseOver prop if desired too.

Anyway let me know your thoughts, happy to publish a separate package if this isn't the direction you want to take.

**Comment by DominicTobias** [comment]
@DanlanNZ still haven't had a chance to look will try to later today, my main concern is the responsive styles bit but I think it must still be able to be responsive - anyway will check to see what you mean!

**Comment by DominicTobias** [comment]
Hi @DanlanNZ, had a look at the PR and it's a good implementation of inline styles.. really, if I wanted to go down the inline styles route this would be it. There are already people using this so it's a breaking change and quite disruptive for them, and as I said apart from convenience it seems a there are a couple disadvantages (just in my opinion). So please create a fork with it! PS for the animation string you can use es6 template strings and then you won't have to put those backslashes in for line breaks. Also I think it's better to do have the unit for padding i.e. `padding: 1px` instead of `1`

**Comment by DanlanNZ** [comment]
thanks for the update and template string suggestion, you know where it is if you ever decide otherwise :smile:
