### ISSUE TITLE
"All crop params are initially optional." When infact they are not

### ISSUE THREAD

**Issue by oskari** [DominicTobias/react-image-crop#439]
Stated in [README](https://github.com/DominicTobias/react-image-crop#crop-required) and in 
https://github.com/DominicTobias/react-image-crop/blob/7c4ddb90a7cf33db2b55a7449f5091f769254d50/src/ReactCrop.tsx#L200-L201
but only the `aspect`-prop is optional: https://github.com/DominicTobias/react-image-crop/blob/7c4ddb90a7cf33db2b55a7449f5091f769254d50/src/ReactCrop.tsx#L164-L171

**Comment by DominicTobias** [comment]
Good point I will update the defs in the next day or 2

**Comment by Slumber86** [comment]
Don't forget to update the interface definition! Thanks!

**Comment by DominicTobias** [comment]
@Slumber86 this should be updated in 9.0.4, are you still experiencing issues?

**Comment by Slumber86** [comment]
@DominicTobias the problem is with 

```ts 
export interface Crop {
  aspect?: number;
  x: number;
  y: number;
  width: number;
  height: number;
  unit: 'px' | '%';
} 
```

We use typescript and we provide the library a `Crop` object
At the moment only aspect is optional, in 9.0.4 this is unchanged. I've looked at the source code and realized that i can provide `Partial<Crop>` instead of `Crop` to make things work, but is better to make it explicit in the docs

**Comment by DominicTobias** [comment]
You should be able to pass in a partial object now: https://github.com/DominicTobias/react-image-crop/blob/master/src/ReactCrop.tsx#L200 but maybe I've missed something. Please check in node_modules you have the right version and restart your IDE and I'll check what's up if the issue persists

**Comment by Slumber86** [comment]
@DominicTobias sure is what I've done. 
but still the Crop object has not optionals, you have to pass a partial. There is a subtle difference but still a difference to point out

**Comment by DominicTobias** [comment]
Do you mean allowing the whole object to be optional (e.g null or
undefined)? I think that works though it wasn’t the original intention.
There are places where the crop is spread …crop which would cause an
exception if executed

**Comment by Slumber86** [comment]
Sure, there is infact a trade-off between internal implementation and develper-friendliness of the APIs. Just highlight the partial usage in the docs!

**Comment by nzayatz14** [comment]
@DominicTobias making the prop `crop` a `Partial <Crop>` object as a parameter fixes the issue of having to pass a full `Crop` into the component, but it does not fix the issue of declaring a local value as a `Crop`.

For example, your current definition of a `Crop` is
```typescript
export interface Crop {
  aspect?: number;
  x: number;
  y: number;
  width: number;
  height: number;
  unit: 'px' | '%';
}
```

so, if I wanted to create a local state variable to store the current crop in my component, it may look something like
```typescript
const [myCrop, setMyCrop] = useState<Crop>({ unit: '%', width: 50, aspect: 1 }); //this throws a type error
```

This particular line, however, would throw a TypeError because my initial state value of `{ unit: '%', width: 50, aspect: 1 }` is missing the parameters `height`, `x`, and `y`.

Changing the type definition of `Crop` to be:
```typescript
export interface Crop {
  aspect?: number;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  unit?: 'px' | '%';
}
```
may just work, though I do not know if you need any of those fields to be required specifically.

Hope this sheds some light on the issue.

**Comment by DominicTobias** [comment]
This has changed in v10 (along with many breaking changes) and is no longer an issue as a complete crop always has to be passed in. Check the release notes for more info.
