### ISSUE TITLE
Download Size To Big

### ISSUE THREAD

**Issue by vitorizkiimanda** [DominicTobias/react-image-crop#451]
Just following demo code on https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o 

and cropped then downloaded image size always way bigger than the original. 

any suggestion how to avoid this?

disclaimer : already tried to lower the "pixelRatio" but the size still way bigger

**Comment by DominicTobias** [comment]
The image was doubled because on retina devices if the canvas isn't double (or more depending on the device) it is more blurry than the image. You would have to scale the canvas down before download. I have changed it to use an image and am not scaling the preview for retina devices so should be ok, though the crop preview still takes a crop of the originally sized image (before it gets scaled up or more likely down in the browser) otherwise users on e.g. a phone would get a really low res image: https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o?file=/src/App.tsx 

If the image wasn't scaled down in the browser though if you right click and save the preview you will see it's true to size now

**Comment by chapeee** [comment]
did anyone get the solution?

**Comment by chapeee** [comment]
well i solved this, anybody who is looking for a solution

` const base64Image = canvas.toDataURL('image/jpeg',0.7);`

Make sure not to use JPG the right context is JPEG.
