### ISSUE TITLE
Why only rectangles can be used

### ISSUE THREAD

**Issue by strongyc** [DominicTobias/react-image-crop#497]
Why only rectangles can be used？
Want to use any graphic

**Comment by DominicTobias** [comment]
All the maths and logic is centered around a rectangle, there's no way it can support other shapes without being completely re-written. It also supports a circle but this is still just a rectangle that is made to look like a circle. You could make it look like other shapes within the rectangle using CSS [clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path) probably but that's it, otherwise you'll need to use a library specifically built to support other shapes
