### ISSUE TITLE
Maybe update docs on how to update preview when changing aspect ratio

### ISSUE THREAD

**Issue by Michael-AT-Corporation** [DominicTobias/react-image-crop#550]
When I changed the aspect ratio for my preview with a button click it didn't update the preview until i moved the cropping area.
After some search i found in an issue that this won't trigger the `onComplete` and that you should call whatever is called by that function manually. 
Also the demo preview from the docs has the same issue: https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o
When you upload an image, toggle the apect to off and change the crop to a small width and then turn aspect back on the preview won't be updated.
Would have saved me quite some time. :)
![image](https://github.com/DominicTobias/react-image-crop/assets/77804353/73b582cd-a3d3-4a95-9880-7521faab3961)

**Comment by DominicTobias** [comment]
Ah yes I'll update the demo at least. I'm wary of fixing this in code to fire a onComplete event because I've ran into infinite loop issues when checking if props changed in `componentDidUpdate` and then firing onChange/onComplete. There are some scenarios with dividing % to px resulting in some small floating point differences that breaks deep comparison, and if the user creates a new object in onComplete then shallow comparison of old and new props will fail each time

**Comment by DominicTobias** [comment]
I've updated the demo at least

```
  function handleToggleAspectClick() {
    if (aspect) {
      setAspect(undefined)
    } else if (imgRef.current) {
      const { width, height } = imgRef.current
      setAspect(16 / 9)
      const newCrop = centerAspectCrop(width, height, 16 / 9)
      setCrop(newCrop)
      if (imgRef.current) {
        const { width, height } = imgRef.current
        setCompletedCrop(convertToPixelCrop(newCrop, width, height))
      }
    }
  }
```
