### ISSUE TITLE
ReactCrop__child-wrapper's width is differ by browser

### ISSUE THREAD

**Issue by junzero741** [DominicTobias/react-image-crop#565]
crop's child-wrapper's size is different by browser.
as you can see below, chrome's version is ideal result.

because of it's width difference, crop selection area is set to wrong aspect. (initial selection area is set to 50%)

(ideal) chrome :
![스크린샷 2023-10-25 오후 2 47 05](https://github.com/DominicTobias/react-image-crop/assets/71166372/d2bf961a-28f2-4699-93db-87d9bce2e60c)

safari:
![스크린샷 2023-10-25 오후 2 46 54](https://github.com/DominicTobias/react-image-crop/assets/71166372/819fbf52-9550-4692-a060-007ae37663fe)

below is html hierarchy (just in case you need it,  h-full is `height: 100% `

![image](https://github.com/DominicTobias/react-image-crop/assets/71166372/ce21300a-2ae4-4153-acaf-6311185e9159)

**Comment by DominicTobias** [comment]
Sorry it took so long to reply. Hm I am in Safari but don't see the same issue as you. Also since `.ReactCrop__child-wrapper` has almost no styling, it should just inherit the size of the parent divs

<img width="1360" alt="Screenshot 2023-11-30 at 21 42 24" src="https://github.com/DominicTobias/react-image-crop/assets/760314/7a639ed1-62e1-46a8-b1ad-26158baba3af">

**Comment by junzero741** [comment]
Sorry, I found out that I set custom style to `.ReactCrop__child-wrapper `. now i dealt with it. million thx for you effort! 👍
