### ISSUE TITLE
Pixel coords for the image crop

### ISSUE THREAD

**Issue by riccardolorenzon** [DominicTobias/react-image-crop#59]
Apparently the additional parameter `pixelCrop` of `onChangeComplete` is always `undefined`. 

And also, is there any way to set the crop on pixel units? Instead of converting it from pixel units to percentage every time in order to use it?

**Comment by DominicTobias** [comment]
Hi @riccardolorenzon updating the README was confusing because that version isn't released yet. RC7 only passes the normal crop object. If you want it to pass pixels then your should also pass the `outputPixelUnits` prop. At the moment there is no way to pass pixels in because it would require another property or for values to specify a unit e.g. instead of `220` it would be `220px` as there is no way to determine whether the passed in values are pixels or percentages. I'll consider it for the next version though. In the mean time you could do the calculation yourself to convert pixels to percentages.

**Comment by riccardolorenzon** [comment]
hi @DominicTobias, thank you for the quick reply. 

Any suggestions on how to get the natural height and width of the image without loading it again?

**Comment by riccardolorenzon** [comment]
I used the natualHeight and naturalWidth img properties: http://www.w3schools.com/jsref/prop_img_naturalheight.asp

**Comment by riccardolorenzon** [comment]
I just updated the component to the last version. 

Is it now possible to specify the crop coordinates using pixels? i can't find that part on the docs.

**Comment by DominicTobias** [comment]
Hi @riccardolorenzon no there isn't and there is no intention of adding this, most other cropping tools out there use pixels so if you prefer that you might be better off with them (it would complicate the code base too much to add support for both). The point of using percentages is so that when the crop is resized it is still correct (responsive) - there is no need to write an algorithm to detect if the crop element resizes, poll for it, and recalc the crop. This makes it smoother and the code simpler (it just works), the drawback is that if you want to pass pixels in then you have to calc them. Although you do get passed the pixels in onComplete and onChange for convenience of passing that to e.g. a backend, you are still supposed to pass in percentages.

**Comment by zackify** [comment]
Doing this is really easy. Here's how my component looks:
```js
getBase64(file) {
    this.setState({ loading: true, file });

    let reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      var image = new Image();
      image.src = reader.result;

      image.onload = () => {
        this.setState({
          loading: false,
          image: reader.result,
          height: image.height,
          width: image.width,
        });
      };
    };
    reader.onerror = error => console.log('Error: ', error);
  }
```

Get the  base64 of a file object, render it to an image, get the height and width. Then, pass the height and width to your cropper props, something like this:

```js

          minWidth: 1920 / image.width * 100,
          minHeight: 350 / image.height * 100,
          maxWidth: 1920 / image.width * 100,
          maxHeight: 350 / image.height * 100,
   
```

Now you have percentages from pixels, for anyone else who needs it :)

**Comment by WaqqarSuleman** [comment]
> I used the natualHeight and naturalWidth img properties: http://www.w3schools.com/jsref/prop_img_naturalheight.asp

Getting naturalWidth and naturalHeight as 0, any idea why?
