### ISSUE TITLE
Initial crop props does not seem to work

### ISSUE THREAD

**Issue by yanickrochon** [DominicTobias/react-image-crop#70]
I initialize the component like this

```jsx
const cropData = {
  keepSelection: true,
  aspect: 1,
  top: 0,
  left: 0,
  width: 100
};

<ReactCrop src={ src } crop={ cropData } />
```

However the selection is not visible on the image (the image is well over 600 x 600). And when the user clicks outside a selection, the selection is discarded.

**Comment by yanickrochon** [comment]
For the `top`, `left` and `width` part, I think I get it, now; the values are relative to the current rendered image (responsive), and not the actual image's dimension. This is confusing, and I presumed that `onChange`, `onComplete`, etc. had their arguments reversed; where `crop` was the actual and proportional to the actual image's source dimension, and `pixelCrop` was the scaled (i.e. responsive) dimension.

This is silly, but since I cannot know in advance the actual rendered size of the element, but I do know the size of the raw image, that crop would've been in relation with the image source, not the responsive image element's dimension...

**Comment by DominicTobias** [comment]
Crop dimensions are set as percentages - so you just set a crop with a width of 100% and a height of 100% (due to an aspect of 1) - so the crop should be filling the whole image - are you sure that isn't happening? I'm currently travelling so can't test with the values you provided yet.

`pixelCrop` is an argument in the callback for your convenience, giving the crop values converted from percentages to pixels in case you need that, it's not for setting back into the `crop` prop

**Comment by yanickrochon** [comment]
OOOoooohhh!!!! 

That makes sense :stuck_out_tongue: I was trying to make sense of the values I got, and couldn't figure it out, I overlooked that possibility. Right, I re-read the docs and it is specified, indeed.

Nothing to see, here!
