### ISSUE TITLE
Disabling new drag crops

### ISSUE THREAD

**Issue by joekur** [DominicTobias/react-image-crop#81]
Wondering if you think it would be suitable to add an option to disable resetting your crop by dragging on an unselected area of the image. Illustrative gif of what I'm talking about:

![drag-crop](https://cloud.githubusercontent.com/assets/1043396/22123808/c5eae000-de52-11e6-9605-ffc3fdcb8a09.gif)

A couple reasons I would like to disable this:
1. On mobile it is very easy to "fat finger" trying to drag one of the handles, and start drawing a new crop.
2. When adding a minWidth/minHeight, the interaction can be very jittery when drawing a new crop. See gif below:

![drag-crop-mins3](https://cloud.githubusercontent.com/assets/1043396/22124021/abf46c60-de53-11e6-8c41-42ab0bb077fb.gif)

Glancing through the source, it looks like it would be as simple as adding a conditional here based on a prop: https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.jsx. I'd be happy to make that PR if you agree with this.

Thanks for your consideration!

**Comment by DominicTobias** [comment]
Hi there is a way of disabling already - pass `disabled={true}` ;)

As for the jittery-ness - yeah when I was writing this I noticed the same behaviour on others too, happens when you cross over the vertical starting point (and possibly on the x axis too). I'd like to some day write a better algorithm for the crop but it's trickier than it seems and quite a pain!
