### ISSUE TITLE
Rotation support

### ISSUE THREAD

**Issue by djfdev** [DominicTobias/react-image-crop#92]
Any plans to add support for rotating the image? Or does anyone have experience rotating the image, while maintaining the proper directionality of the cropper? Basically I'm thinking something along the lines of the following:

- Strip out EXIF rotation data before `onImageLoaded` callback is fired
- Add support for a `rotation` prop (or potentially `crop` attribute), which accepts a number of degrees to rotate the image clockwise

I'd like to work on this, but I'd want to find out from the project maintainers if this is potentially out of scope for this project (or impossible, if I'm missing something). Thanks!

EDIT: Realizing that EXIF manipulation is definitely out of scope here. But it would be nice if I could specify a particular CSS transform for how the image is displayed based on a `rotation` prop.

**Comment by DominicTobias** [comment]
Hi @djfdev, sorry but this is indeed beyond the scope of this library. It's too specific a use-case and I don't have the inclination to support that much of an extended feature set tbh. But if I was you I would create a higher order component (one which wraps this one or another lib) and adds that prop and does what you desire, it sounds like it could be pretty agnostic of the actual cropping component which sits underneath so that could be swapped out if ever needed.

**Comment by toddmyphoto** [comment]
Hey @djfdev 
I'm using this library and doing rotation as well. I created a rotation button that rotates by -90 deg (although you could create a slider or other controller that does in smaller increments). I then update my rotation in state and pass that through to the ReactCrop component as imageStyle props. If I pass a `{transform: 'rotate(' + this.state.rotation + 'deg)'}` to the imageStyle props on the ReactCrop component, it works pretty well.
Hope this helps!

**Comment by nikhilwankhede98** [comment]
Hi.. I am having functionality of crop and rotate an image using this package and I am getting the cropped image url using 
"canvas.toDataURL("image/jpeg", 1)". I am generating this url to display the cropped image. But the issue I am facing is that while rotating, I have to maintain the rotation degree state in my Component. But instead,  I want to add the rotation property in the imag url itself that I am generating since I need to pass this url to the backend.. Does anyone have a solution to this requirement?
