### ISSUE TITLE
onChange not called when crop is changed on load

### ISSUE THREAD

**Issue by shogowada** [DominicTobias/react-image-crop#99]
Maybe this is by design, but `onChange` is not called when the initial crop was adjusted on load.

```jsx
const crop = { // This crop will be adjusted on load
  x: 20,
  width: 60,
  aspect: 1
}
<ReactCrop src="foo.jpg" crop={crop}
  onChange={(newCrop) => {setState(newCrop);}} // but it's not called on load
  onImageLoad={(initialCrop) => {setState(initialCrop);}} // so I need to do this, too, in case user didn't change the crop region.
/>
```

**Comment by borlaym** [comment]
Ran into the same issue, I'd argue this is fine as it is, since technically it's not a change. If you want to react to changes by for example enabling a save button, you don't want that to fire on initial load.

**Comment by DominicTobias** [comment]
Hi yep as Marton says this was by design, I'm not exactly sure which
behaviour makes sense to most people, but it's true that something like a
Dave or cancel button would benefit from the current behaviour.

I think you could do it a different way though - set or initial crop on the
state e.g state.crop and on change modify that crop object, then you
wouldn't need the onImageLoaded callback - I'm not sure why they are two
seperate objects at the moment!

**Comment by shogowada** [comment]
> set your initial crop on the state

Sorry, my example is incomplete, but that's what I'm actually doing. Issue is, my initial crop doesn't have `y` or `height` because I'm letting the library to adjust them during the initialization. During the initialization, the library fills `y` and `height`, but I cannot catch that change via `onChange`.

But I see a valid use case for the current behavior too, so that's fine. I wanted to make sure whether this is a bug or by design.

I made [a PR](https://github.com/DominicTobias/react-image-crop/pull/100) to communicate that better.
